before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
scoop:
  name: kubectl-sshd
  commit_author:
    name: callowaysutton
    email: me@callowaysutton.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: nfpm-default
    package_name: kubectl-sshd
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Calloway Sutton
    homepage: https://callowaysutton.com/
    maintainer: Calloway Sutton <me@callowaysutton.com>
    description: SSH into a kubernetes pod serial console, based on libvirt-sshd by Nate Sales
    license: GNU GPL-3.0
    section: utils
    priority: extra

    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - nfpm-default
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/
